name: release

on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/mandarin-tamer
      # This links the workflow to your PyPI project page
      # Helps with tracking deployments and provides a direct link
    permissions:
      id-token: write # Required for trusted publishing
      contents: write # Required for creating releases

    steps:
      - uses: actions/checkout@v4
        # This step checks out your repository code into the GitHub Actions runner
        # Without this, the runner wouldn't have access to your project files

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          # This step installs Python 3.11 on the runner
          # We need Python to build and publish your package

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build
        # This step:
        # 1. Upgrades pip to latest version to avoid any compatibility issues
        # 2. Installs 'build' to create wheel and sdist packages

      - name: Build package
        run: python -m build
        # This creates two distribution formats:
        # 1. A wheel file (.whl) - A built package format
        # 2. A source distribution (.tar.gz) - Raw source code package
        # Both are needed for maximum compatibility with different systems

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # This step publishes your built packages to PyPI
        # Uses GitHub's OIDC token for trusted publishing
        # No credentials needed - uses trusted publishing

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
          generate_release_notes: true
